void ticTacToe(void);
void writeMovesToBoard(int *moves);
void drawScore(int score1, int score2);
void drawWinningLine(int line);
void drawGrid(void);
void redrawGrid(int line);
int clearScreen(void);
void sysOutMenu(void);
void sysOut(int write, int player);
void playEnding(void);
